spring:
  application:
    name:  Todo-user
  datasource:
    url: jdbc:postgresql://localhost:5432/todo-user
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    
    
    
    
server:
  port: 8081
  
